### ISSUE TITLE
Daftar upcoming livestream kadang2 nggak lengkap

### ISSUE THREAD

**Issue by anakaiti** [sunnyegg/vim-app#17]
Kadang2 ada upcoming livestream yg sudah ada di Youtube tapi nggak kelihatan di VIM.

**Comment by sunnyegg** [comment]
Betul, ini karena VIM akan memeriksa secara berkala (sekarang dengan jangka waktu 3 jam 30 menit).
Jadi misal ada vtuber yg upload jadwal jam 1, maka tidak akan kelihatan di VIM sebelum jam 3:30 (dan kelipatannya).
Issue ini akan tetap ada selama VIM belum request untuk penambahan quota per hari ke Youtube Data API.

Terima kasih

**Comment by sunnyegg** [comment]
Sekarang setiap 4 jam

**Comment by anakaiti** [comment]
![Kyknya lebih dari 4 jam.](https://user-images.githubusercontent.com/5457202/82179889-94e4cf00-9909-11ea-8c43-60f5c871a292.png) 2 of the streams are dead lol.

**Comment by sunnyegg** [comment]
Ah, itu bug di sisi VIM, masih belum di-handle.
Soalnya jika Owner menghapus atau dijadikan private, videoId nya akan kosong (tidak ditemukan), karena VIM belum meng-handle, maka VIM bingung jika videoId nya kosong akan diapakan (akhirnya dibiarkan).

Akan saya update secepatnya!
